### ISSUE TITLE
Arreglado la muestra de mimetypes pero no descomprime

### ISSUE THREAD

**Issue by CalebCDE** [x7bit/unarchiver_opendingux#1]
No descomprime nada, quizás sea cosa del mimetype... investigo

**Comment by x7bit** [comment]
Muy buenas Tana, ¿será cosa del Rogue? Yo acabo de probar con zip y funciona. Comprobado también que el opk que tengo en la consola tiene el mismo md5 que el que está aquí. Luego pruebo con todos los formatos que me faltan por si acaso alguno quedara mal.

Para comprobar el mimetype del comprimido, desde el st-terminal haz un:
`file -bi "archivo" | cut -d';' -f1`
Y mira que te devuelve y si cuadra con el _case_ del unarchiver.sh

Luego comprobar que también que el descompresor (ejecutable) está en el sistema:
`which 7zr`
o
`which unrar`

Otra cosa que no sé si está bien o mal son los separadores del mimetypes del desktop, que no estoy seguro de si son comas o punto y comas. Aquí está con comas, y me da que está mal porque viendo las especificaciones de los .desktops de linux (o sea viendo documentación general, no específica de los opks) dicen que van separados por punto y coma, a ver si va ser eso.

**Comment by x7bit** [comment]
Buenas de nuevo, he subido una nueva versión que comprueba que los ejecutables que descomprimen existen en el sistema imprimiendo un error si falta algo. Por cierto, confirmado que el separador de los MIMEs es el punto y coma, si los pones con comas no te reconoce los MIMES y entonces te lista todos los ficheros. Otra cosa a tener en cuenta es que si por ejemplo el unizp no está ni instalado, entonces es probable también que el MIME de los zips no esté registrado en el sistema, y lo detecte como un binario (octet-stream), por eso no entra en el case y por eso no descomprime. La nueva versión si no es un MIME esperado te muestra un mensaje de error diciendo el MIME que dice el sistema que tiene.

**Comment by x7bit** [comment]
Prueba por favor la nueva versión, debería de estar solucionado muchos de esos pequeños problemas con los mimes y demás.
